### ISSUE TITLE
1.0.6: Parse error in fonts/language_cyrillic.xml

### ISSUE THREAD

**Issue by fnatter** [opencollab/jlatexmath#33]
hello jlatexmath developers,

many thanks for this excellent library!

I have a small problem in 1.0.6 when rendering a formula "тся" in Freeplane
for the first time (on Freeplane startup):

```
WARNING: Problem with command text at position 4:10
fonts/language_cyrillic.xml
org.scilab.forge.jlatexmath.ParseException: Problem with command text at position 4:10
fonts/language_cyrillic.xml
	at org.scilab.forge.jlatexmath.PredefMacroInfo.invokeID(PredefMacroInfo.java:593)
	at org.scilab.forge.jlatexmath.PredefMacroInfo.invoke(PredefMacroInfo.java:70)
	at org.scilab.forge.jlatexmath.TeXParser.processCommands(TeXParser.java:1398)
	at org.scilab.forge.jlatexmath.TeXParser.processEscape(TeXParser.java:1238)
	at org.scilab.forge.jlatexmath.TeXParser.parse(TeXParser.java:712)
	at org.scilab.forge.jlatexmath.TeXFormula.<init>(TeXFormula.java:284)
	at org.scilab.forge.jlatexmath.TeXFormula.<init>(TeXFormula.java:268)
	at org.freeplane.plugin.latex.TeXText.createTeXIcon(TeXText.java:39)
	at org.freeplane.plugin.latex.LatexRenderer.getIcon(LatexRenderer.java:90)
```

Please tell me if you cannot reproduce this easily. In that case I will (try to) provide a minimal example.

Thanks and Best Regards,
Felix

**Comment by dpolivaev** [comment]
You can close this issue. Freeplane build configuration was a problem and now we fixed it.

**Comment by sylvestre** [comment]
Thanks for the feedback.
